version: '{build}'

branches:
  only:
  - main

image: Visual Studio 2019
configuration: Release

before_build:
- cmd: dotnet restore

build:
  verbosity: minimal

artifacts:
- path: '**\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: GznQUnVxkHabLmXzQtNsrmv2dgEmFx64ToTsDs/TZJzWqLo1bFazhhMFAFYXf4Ch
  on:
    appveyor_repo_tag: true